import { AppSidebar } from "@/components/app-sidebar";
import { IconSidebar } from "@/components/icon-sidebar";
import QueryProvider from "@/components/providers/query-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from "@/features/auth/auth.context";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          {/* <div className="flex min-h-svh"> */}
            {/* <IconSidebar />
            <SidebarProvider>
              <AppSidebar /> */}
              <main className="flex flex-1 flex-col">
                {/* <header className="flex h-12 items-center gap-2 border-b px-4">
                  <SidebarTrigger />
                </header> */}
                <div className="flex-1">
                  <QueryProvider>
                    <AuthProvider>
                      {children}
                    </AuthProvider>
                    <Toaster richColors position="top-right" />
                  </QueryProvider>
                </div>
              </main>
            {/* </SidebarProvider> */}
          {/* </div> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
