export enum NotificationTemplateCode {
  // Auth
  WELCOME_EMAIL = 'WELCOME_EMAIL',
  RESET_PASSWORD = 'RESET_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',

  // Workspace
  INVITE_MEMBER = 'INVITE_MEMBER',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',

  // Project
  PROJECT_CREATED = 'PROJECT_CREATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_COMPLETED = 'TASK_COMPLETED',
}
